name: lumi_learn_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.3.0+4

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  provider: ^6.0.0 # add this line
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
  file_picker: ^6.1.1 # Add this line
  audioplayers: ^6.4.0
  image_picker: ^0.8.7

  
  # UI & Fonts
  google_fonts: ^6.1.0 # Updated to the latest stable version
  flutter_svg: ^2.0.10 # Update to avoid conflicts
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  material_symbols_icons: ^4.2805.1
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.2
  mime: ^1.0.4
  animated_text_kit: ^4.2.3
  record: ^5.2.1
  speech_to_text: ^7.0.0
  path: ^1.9.0
  path_provider: ^2.0.15
  flutter_native_splash: ^2.4.4
  url_launcher: ^6.0.9
  permission_handler: ^11.0.0
  share: ^2.0.4
  sign_in_with_apple: ^6.1.4
  intl: ^0.20.2
  purchases_flutter: ^8.7.2
  flutter_math_fork: ^0.7.3
  flutter_doc_scanner: ^0.0.16
  crop_your_image: ^2.0.0
  image_cropper: ^5.0.0
  camera: ^0.10.5+2
  uuid: ^4.5.1




  


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/photos/pp2.png"  # <-- Use your new icon here
  remove_alpha_ios: true             # <-- Ensures the App Store icon has no transparency

flutter_native_splash:
  color: "#0A0A0A"                    # â† Your splash background color
  image: assets/splash/moon_splash.png      # Replace with your logo image
  android: true
  ios: true
  fullscreen: true



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/milky_way.png
    # - assets/planets/red1.png
    # - assets/planets/ring1.png
    - assets/astronaut/
    - assets/planets/
    - assets/galaxies/
    - assets/stars/
    - assets/fonts/
    - assets/images/
    - assets/planets/
    - assets/backgrounds/
    - assets/sounds/
    - assets/pfp/
    - assets/splash/
    - assets/onboarding/
    - assets/icons/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
